name: Deploy Site

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Swift 5.4
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.4'
      - name: Verify Swift version
        run: swift --version
      - name: Install Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          swift build -c release
          mkdir $HOME/.local/bin
          install .build/release/publish-cli $HOME/.local/bin/publish
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Write Deploy Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          known_hosts: github.com
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@swiftpackageindex.com"
          git config --global user.name "GitHub Actions Runner"
      - name: Generate Static Site
        run: make deploy
        env:
          PUBLISH_ENV: production
