# Copyright 2020-2021 Dave Verwer, Sven A. Schmidt, and other contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Deploy Site

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Swift
        uses: fwal/setup-swift@v1
      - name: Verify Swift version
        run: swift --version
      - name: Install Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          swift build -c release
          mkdir $HOME/.local/bin
          install .build/release/publish-cli $HOME/.local/bin/publish
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Write Deploy Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          known_hosts: github.com
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@swiftpackageindex.com"
          git config --global user.name "GitHub Actions Runner"
      - name: Generate Static Site
        run: make deploy
        env:
          PUBLISH_ENV: production
