name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app && xcodebuild -version
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make
    - name: Write Deploy Key
      run: |
        echo $ACTIONS_DEPLOY_KEY > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    - name: Generate Static Site
      run: env PUBLISH_ENV=production && publish generate && publish deploy
